FROM python:3.8.3

COPY ./requirements.txt /work/requirements.txt
RUN pip install -r requirements.txt

ARG USERNAME=djangossh
ARG USERPASS=shhimworkinghere

# TODO: move this to dev build before production
RUN apt-get update && apt-get -y install ssh whois
RUN useradd -ms /bin/bash $USERNAME
RUN usermod --password $(echo "$USERPASS" | mkpasswd -s) $USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

RUN mkdir /home/$USERNAME/.ssh && touch /home/$USERNAME/.ssh/authorized_keys
USER root

COPY ./src/djangosrc/secrets/djangossh.key.pub /home/$USERNAME/.ssh/authorized_keys

# End of SSH

RUN mkdir /work/
WORKDIR /work/

COPY ./entrypoint.sh /script/entrypoint.sh

ENV PYTHONUNBUFFERED 1

RUN chmod +x /script/entrypoint.sh

ENTRYPOINT ["/script/entrypoint.sh"]
