FROM python:3.8.3-alpine3.11 as base

RUN mkdir /work/
WORKDIR /work/

COPY ./requirements.txt /work/requirements.txt
RUN pip install -r requirements.txt

COPY ./src/ /work/
ENV PYTHONUNBUFFERED 1

FROM base as prod

CMD python manage.py runserver 0.0.0.0:8000