FROM python:3.8.3

ARG USERNAME=djangossh
ARG USERPASS=shhimworkinghere

# TODO: move this to dev build before production
RUN apt-get update && apt-get -y install openssh-server whois
RUN useradd -ms /bin/bash $USERNAME
RUN usermod --password $(echo "$USERPASS" | mkpasswd -s) $USERNAME
RUN apt purge -y whois && apt -y autoremove && apt -y autoclean && apt -y clean
USER $USERNAME
WORKDIR /home/$USERNAME
COPY entrypoint.sh entrypoint.sh
RUN chmod +x /entrypoint.sh
USER $USERNAME
RUN mkdir /home/$USERNAME/.ssh && touch /home/$USERNAME/.ssh/authorized_keys
USER root
VOLUME /home/$USERNAME/.ssh
VOLUME /etc/ssh

# End of SSH

RUN mkdir /work/
WORKDIR /work/

COPY ./requirements.txt /work/requirements.txt
RUN pip install -r requirements.txt

#COPY ./python/src/ /work/
ENV PYTHONUNBUFFERED 1

#CMD python manage.py runserver 0.0.0.0:8000
CMD ["/entrypoint.sh"]